Repository BT3103AppDev1/final-project-l1-final-project-group-12, pull requests merged in 2023-11, with the labels that each got.

#22 Added functions to handle for the optimise portfolio
  app/api/routes/deleteDataRoutes.js
  app/api/routes/readDataRoutes.js
  app/controllers/deleteDataController.js
  app/controllers/readDataController.js
  docs/DeveloperApiGuide.md
  package-lock.json
Labels: bug, enhancement

#21 Portfolio page
  .DS_Store
  .gitignore
  .vscode/extensions.json
  app/api/server.js
  app/firebase.js
  app/models/__pycache__/Trade.cpython-311.pyc
  index.html
  package.json
  src/.DS_Store
  src/assets/.DS_Store
  src/assets/crossIcon.png
  src/assets/deleteIcon.png
  src/assets/editIcon.png
  src/assets/fire.png
  src/assets/gainIcon.png
  src/assets/loseIcon.png
  src/assets/piechartIcon.png
  src/assets/placeholder_to_delete
  src/assets/tableIcon.png
  src/assets/tickIcon.png
  src/components/.DS_Store
  src/components/Loading.vue
  src/components/Login/ForgetPassword.vue
  src/components/Login/LoginBox.vue
  src/components/Navigation.vue
  src/components/Portfolio/AddTrade.vue
  src/components/Portfolio/OptimisationTab.vue
  src/components/Portfolio/PortfolioAssetView.vue
  src/components/Portfolio/PortfolioPieChart.vue
  src/components/Portfolio/PortfolioStatistics.vue
  src/components/Portfolio/PortfolioTable.vue
  src/firebase.js
  src/firebasefunc.js
  src/router/index.js
  src/uifire.js
  src/views/.DS_Store
  src/views/Login.vue
  src/views/Portfolio.vue
Labels: enhancement

#31 Fix bug for watchlist page
  src/components/Equities/Box.vue
  src/components/Equities/SearchResultsContent.vue
  src/components/Watchlist/AddToWatchlist.vue
  src/components/Watchlist/WatchlistHeader.vue
  src/components/Watchlist/WatchlistTable.vue
  src/views/Watchlist.vue
Labels: bug, enhancement

#33 Portfolio display (Resolve bug + add tooltip for portfolio statistics)
  .DS_Store
  src/.DS_Store
  src/assets/.DS_Store
  src/assets/infoIcon.png
  src/components/.DS_Store
  src/components/Portfolio/AddTrade.vue
  src/components/Portfolio/OptimisationTab.vue
  src/components/Portfolio/PortfolioAssetView.vue
  src/components/Portfolio/PortfolioStatistics.vue
  src/components/Portfolio/PortfolioTable.vue
  src/views/Portfolio.vue
Labels: bug, enhancement

#34 Fixingbrowserbr
  src/components/Login/LoginBox.vue
  src/views/Login.vue
Labels: bug
